// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/auth/callback": {
    params: {};
  };
  "/auth/logout": {
    params: {};
  };
  "/onboarding": {
    params: {};
  };
  "/select": {
    params: {};
  };
  "/feed": {
    params: {};
  };
  "/players": {
    params: {};
  };
  "/stats": {
    params: {};
  };
  "/management": {
    params: {};
  };
  "/manage-coaches": {
    params: {};
  };
  "/manage-players": {
    params: {};
  };
  "/compare": {
    params: {};
  };
  "/compare-stats-only": {
    params: {};
  };
  "/compare-money": {
    params: {};
  };
  "/uploads": {
    params: {};
  };
  "/video/:id": {
    params: {
      "id": string;
    };
  };
  "/player/:id": {
    params: {
      "id": string;
    };
  };
  "/team/:id": {
    params: {
      "id": string;
    };
  };
  "/create-team": {
    params: {};
  };
  "/insights": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/auth/callback" | "/auth/logout" | "/onboarding" | "/select" | "/feed" | "/players" | "/stats" | "/management" | "/manage-coaches" | "/manage-players" | "/compare" | "/compare-stats-only" | "/compare-money" | "/uploads" | "/video/:id" | "/player/:id" | "/team/:id" | "/create-team" | "/insights" | "/profile" | "/*";
  };
  "routes/login/index.tsx": {
    id: "routes/login/index";
    page: "/login";
  };
  "routes/auth/callback.ts": {
    id: "routes/auth/callback";
    page: "/auth/callback";
  };
  "routes/auth/logout.ts": {
    id: "routes/auth/logout";
    page: "/auth/logout";
  };
  "layouts/protected-layout.tsx": {
    id: "layouts/protected-layout";
    page: "/" | "/onboarding" | "/select" | "/feed" | "/players" | "/stats" | "/management" | "/manage-coaches" | "/manage-players" | "/compare" | "/compare-stats-only" | "/compare-money" | "/uploads" | "/video/:id" | "/player/:id" | "/team/:id" | "/create-team" | "/insights" | "/profile";
  };
  "routes/root-redirect.ts": {
    id: "routes/root-redirect";
    page: "/";
  };
  "routes/onboarding.tsx": {
    id: "routes/onboarding";
    page: "/onboarding";
  };
  "routes/start.tsx": {
    id: "routes/start";
    page: "/select";
  };
  "routes/feed.tsx": {
    id: "routes/feed";
    page: "/feed";
  };
  "routes/players.tsx": {
    id: "routes/players";
    page: "/players";
  };
  "routes/stats.tsx": {
    id: "routes/stats";
    page: "/stats";
  };
  "routes/management.tsx": {
    id: "routes/management";
    page: "/management";
  };
  "routes/ManageCoachesPage.tsx": {
    id: "routes/ManageCoachesPage";
    page: "/manage-coaches";
  };
  "routes/ManagePlayersPage.tsx": {
    id: "routes/ManagePlayersPage";
    page: "/manage-players";
  };
  "routes/compare.tsx": {
    id: "routes/compare";
    page: "/compare";
  };
  "routes/compare-stats-only.tsx": {
    id: "routes/compare-stats-only";
    page: "/compare-stats-only";
  };
  "routes/compare-money.tsx": {
    id: "routes/compare-money";
    page: "/compare-money";
  };
  "routes/uploads.tsx": {
    id: "routes/uploads";
    page: "/uploads";
  };
  "routes/video.$id.tsx": {
    id: "routes/video.$id";
    page: "/video/:id";
  };
  "routes/player.$id.tsx": {
    id: "routes/player.$id";
    page: "/player/:id";
  };
  "routes/team.$id.tsx": {
    id: "routes/team.$id";
    page: "/team/:id";
  };
  "routes/create-team.tsx": {
    id: "routes/create-team";
    page: "/create-team";
  };
  "routes/insights.tsx": {
    id: "routes/insights";
    page: "/insights";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/$.ts": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/login/index": typeof import("./app/routes/login/index.tsx");
  "routes/auth/callback": typeof import("./app/routes/auth/callback.ts");
  "routes/auth/logout": typeof import("./app/routes/auth/logout.ts");
  "layouts/protected-layout": typeof import("./app/layouts/protected-layout.tsx");
  "routes/root-redirect": typeof import("./app/routes/root-redirect.ts");
  "routes/onboarding": typeof import("./app/routes/onboarding.tsx");
  "routes/start": typeof import("./app/routes/start.tsx");
  "routes/feed": typeof import("./app/routes/feed.tsx");
  "routes/players": typeof import("./app/routes/players.tsx");
  "routes/stats": typeof import("./app/routes/stats.tsx");
  "routes/management": typeof import("./app/routes/management.tsx");
  "routes/ManageCoachesPage": typeof import("./app/routes/ManageCoachesPage.tsx");
  "routes/ManagePlayersPage": typeof import("./app/routes/ManagePlayersPage.tsx");
  "routes/compare": typeof import("./app/routes/compare.tsx");
  "routes/compare-stats-only": typeof import("./app/routes/compare-stats-only.tsx");
  "routes/compare-money": typeof import("./app/routes/compare-money.tsx");
  "routes/uploads": typeof import("./app/routes/uploads.tsx");
  "routes/video.$id": typeof import("./app/routes/video.$id.tsx");
  "routes/player.$id": typeof import("./app/routes/player.$id.tsx");
  "routes/team.$id": typeof import("./app/routes/team.$id.tsx");
  "routes/create-team": typeof import("./app/routes/create-team.tsx");
  "routes/insights": typeof import("./app/routes/insights.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/$": typeof import("./app/routes/$.ts");
};